### ISSUE TITLE
undefined symbol while running realm 10.46.0 

### ISSUE THREAD

**Issue by dsp08** [realm/realm-swift#8612]
### How frequently does the bug occur?

Always

### Description

we have an app which uses realm to store data locally. Very strange problem occurs when updating to 10.46.0 version for apple's new privacy requirement. When we run the app in debug mode it's giving compilation error when built. 

### Stacktrace & log output

```shell
protocol witness for RealmSwift.RealmCollection.first.getter : A.Element? in conformance RealmSwift.List<A> : RealmSwift.RealmCollection in RealmSwift, referenced from:
      static GWTCare.GlobalShipsPartyMembership.currentGlobalShipsProduct() -> GWTCare.GlobalShipsProduct? in Parser+Login.o
  protocol witness for RealmSwift.RealmCollection.last.getter : A.Element? in conformance RealmSwift.Results<A> : RealmSwift.RealmCollection in RealmSwift, referenced from:
      static GWTCare.GlobalShipsPartyMembership.currentGlobalShipsMembershipPeriod() -> GWTCare.GlobalShipsMembershipCurrentPeriod? in Parser+Login.o
      static GWTCare.GlobalShipsPartyMembership.currentGlobalShipsProduct() -> GWTCare.GlobalShipsProduct? in Parser+Login.o
  protocol witness for RealmSwift.RealmCollection.first.getter : A.Element? in conformance RealmSwift.Results<A> : RealmSwift.RealmCollection in RealmSwift, referenced from:
      (extension in GWTCare):RealmSwift.Realm.currentGlobalShipsParty() -> GWTCare.GlobalShipsParty? in GlobalShipsParty.o
      (extension in GWTCare):RealmSwift.Realm.reference(of: GWTCare.PartyReferenceTypeRef) -> GWTCare.PartyReference? in GlobalShipsParty.o
      (extension in GWTCare):RealmSwift.Realm.feature(of: GWTCare.ProductFeatureRef) -> GWTCare.GlobalShipsProductFeature? in GlobalShipsProductFeature.o
      static GWTCare.GlobalShipsProductFeature.getFeatureLinked(Swift.Int, Swift.Int) -> GWTCare.GlobalShipsProductFeatureLinks? in GlobalShipsProductFeature.o
      (extension in GWTCare):RealmSwift.Realm.productFeature(of: Swift.Int) -> GWTCare.GlobalShipsProductFeature? in GlobalShipsProductFeature.o
      GWTCare.GlobalShipsProductFeature.eventType() -> GWTCare.EventTypeRef? in GlobalShipsProductFeature.o
      GWTCare.GlobalShipsProductFeature.healthAttributeType() -> GWTCare.PartyAttributeTypeRef in GlobalShipsProductFeature.o
```

### Can you reproduce the bug?

Always

### Version

10.46.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 17.5.1

### Build environment

Xcode version: 15.2
Dependency manager and version: 10.46.0
