### ISSUE TITLE
Error in linking phase when migrating from Cocoapods to Swift Package Manager

### ISSUE THREAD

**Issue by spenceralderson** [realm/realm-swift#7526]
#### Expected results
Migrate from Cocoapods to Swift Package manager and build my project.

#### Actual Results
Error during linking phase while building RealmCore

#### Steps & Code to Reproduce
Getting this error when trying to build after deintegrating pods and adding Realm to the project via SPM:

```
Undefined symbols for architecture x86_64:
  "_SecTrustSetAnchorCertificates", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SSLWrite", referenced from:
      realm::util::network::ssl::Stream::do_ssl_write(char const*, unsigned long) in RealmCore.o
  "_SecTrustEvaluate", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SecTrustGetCertificateCount", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SecTrustGetCertificateAtIndex", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SSLCopyPeerTrust", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SSLHandshake", referenced from:
      realm::util::network::ssl::Stream::do_ssl_handshake() in RealmCore.o
  "_SSLClose", referenced from:
      realm::util::network::ssl::Stream::do_ssl_handshake() in RealmCore.o
      realm::util::network::ssl::Stream::do_ssl_shutdown() in RealmCore.o
  "_SSLSetPeerDomainName", referenced from:
      realm::util::network::ssl::Stream::ssl_set_host_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::error_code&) in RealmCore.o
  "_SSLRead", referenced from:
      realm::util::network::ssl::Stream::do_ssl_read(char*, unsigned long) in RealmCore.o
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in RealmCore.o
      ___llvm_profile_runtime_user in Bid.o
  "_SecCertificateCreateWithData", referenced from:
      realm::util::network::ssl::Context::load_pem_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::nullptr_t, std::__1::error_code&) in RealmCore.o
  "_SSLSetIOFuncs", referenced from:
      realm::util::network::ssl::Stream::ssl_init() in RealmCore.o
  "_SSLCreateContext", referenced from:
      realm::util::network::ssl::Stream::ssl_init() in RealmCore.o
  "_SSLSetSessionOption", referenced from:
      realm::util::network::ssl::Stream::ssl_init() in RealmCore.o
  "_kSecAttrAccessibleAfterFirstUnlock", referenced from:
      realm::keychain::(anonymous namespace)::set_key(std::__1::vector<char, std::__1::allocator<char> > const&, __CFString const*, __CFString const*) in RealmCore.o
  "_kSecAttrService", referenced from:
      realm::keychain::(anonymous namespace)::build_search_dictionary(__CFString const*, __CFString const*, realm::util::Optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) in RealmCore.o
  "_SecTrustSetAnchorCertificatesOnly", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_kSecClassGenericPassword", referenced from:
      realm::keychain::(anonymous namespace)::build_search_dictionary(__CFString const*, __CFString const*, realm::util::Optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) in RealmCore.o
  "_kSecValueData", referenced from:
      realm::keychain::(anonymous namespace)::set_key(std::__1::vector<char, std::__1::allocator<char> > const&, __CFString const*, __CFString const*) in RealmCore.o
  "_kSecAttrAccount", referenced from:
      realm::keychain::(anonymous namespace)::build_search_dictionary(__CFString const*, __CFString const*, realm::util::Optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) in RealmCore.o
  "_kSecReturnData", referenced from:
      realm::keychain::(anonymous namespace)::build_search_dictionary(__CFString const*, __CFString const*, realm::util::Optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) in RealmCore.o
  "_SecCertificateCopyData", referenced from:
      realm::util::network::ssl::Context::ssl_use_verify_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::error_code&) in RealmCore.o
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SecItemCopyMatching", referenced from:
      realm::keychain::(anonymous namespace)::get_key(__CFString const*, __CFString const*) in RealmCore.o
  "_SecCopyErrorMessageString", referenced from:
      realm::util::network::SecureTransportErrorCategory::message(int) const in RealmCore.o
  "_kSecAttrAccessible", referenced from:
      realm::keychain::(anonymous namespace)::set_key(std::__1::vector<char, std::__1::allocator<char> > const&, __CFString const*, __CFString const*) in RealmCore.o
  "_kSecClass", referenced from:
      realm::keychain::(anonymous namespace)::build_search_dictionary(__CFString const*, __CFString const*, realm::util::Optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) in RealmCore.o
  "_SSLSetConnection", referenced from:
      realm::util::network::ssl::Stream::ssl_init() in RealmCore.o
  "_SecTrustEvaluateWithError", referenced from:
      realm::util::network::ssl::Stream::verify_peer() in RealmCore.o
  "_SecItemAdd", referenced from:
      realm::keychain::(anonymous namespace)::set_key(std::__1::vector<char, std::__1::allocator<char> > const&, __CFString const*, __CFString const*) in RealmCore.o
  "_SSLGetSessionState", referenced from:
      realm::util::network::ssl::Stream::ssl_read(char*, unsigned long, std::__1::error_code&, realm::util::network::Service::Want&) in RealmCore.o
      realm::util::network::ssl::Stream::do_ssl_shutdown() in RealmCore.o
  "_SSLSetProtocolVersionMin", referenced from:
      realm::util::network::ssl::Stream::ssl_init() in RealmCore.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Same error appears for building on device but for arm, The Apple Security framework is present in the project that we are trying to build.  The workspace has multiple modules, one of which is able to build without this failure while all the others that are included in the workspace fail at the linking phase. 

#### Core version
Core version: 10.17.0

**Comment by spenceralderson** [comment]
Hi @pavel-ship-it, thanks for the prompt response. The Apple Security framework is included in the target that is failing to build. 
![image](https://user-images.githubusercontent.com/13324643/141520931-ea3e54e1-0823-44e0-a3cb-e7fef957bab5.png)
I have also tried with realm 10.18.0 and the same issue occurs. I have tried with the latest Xcode 13.1 and 13.0, same error when building. The reason I had initially posted this as an issue is RealmCore is because I'm getting this failure when Xcode is trying to build the target that we are including RealmSwift in 
![image](https://user-images.githubusercontent.com/13324643/141521354-78a06399-e5e2-4527-8a47-d3935fdafd04.png)

Hope this helps, Thanks!

**Comment by pavel-ship-it** [comment]
Hi @spenceralderson ,
Unfortunately I cannot reproduce it. Is it possible to share the source code with me?

**Comment by spenceralderson** [comment]
Hi @pavel-ship-it Thank again for getting back to me. Unfortunately I cannot share my source code with you but I can share this sample project I've seen linked in another older and closed issue that I've modified to get the same error. 

Original Project: https://github.com/dianaafanador3/RealmModulesProjectsPlaygorunds/tree/master

my modified sample project with the same error I'm experiencing: https://github.com/spenceralderson/RealmCoreSampleApp

In my linked repo I bumped Realm to version 10.18.0 and added the security framework to each target that has RealmCore as a Package Dependency. Please open the workspace with Xcode 13.1 and try and build.

 Ive included an image of the sample project failing with the same errors I'm receiving: 
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/13324643/142049676-6833c09e-23af-485f-8fe9-b79e10d5f93b.png">

Thanks again and let me know if I can provide further details!

**Comment by pavel-ship-it** [comment]
@spenceralderson i'll try that one today and get back with my results.

**Comment by pavel-ship-it** [comment]
I can reproduce it

**Comment by spenceralderson** [comment]
Ok, glad to hear. Please let me know if you find the solution.

**Comment by yasheedv** [comment]
Facing the same issue. Did you find any solution?

**Comment by spenceralderson** [comment]
@yasheedv No solution found yet.

**Comment by spenceralderson** [comment]
Hey @pavel-ship-it, wondering if you had any updates on this?

**Comment by chunyang-wen** [comment]
Any update on this?

**Comment by dianaafanador3** [comment]
HI @chunyang-wen Seems like the Security framework is not been linked if we have different modules sharing the same dependency. I tested forcing this on the Package.swift file on Realm Core and seems like it is working.
I added a PR to fix on Core, you can follow this here (https://github.com/realm/realm-core/pull/5111)

**Comment by spenceralderson** [comment]
Thats great, thanks @dianaafanador3!

**Comment by dianaafanador3** [comment]
This will need to first get merged, then a release from core and lastly one from our SDK, I linked the PR and the Changelog to this issue so yo can get updates on every step.

**Comment by chunyang-wen** [comment]
The latest version 10.20.2 compiles with Xcode 13.2.1 on Monetry.

**Comment by dianaafanador3** [comment]
Fixed by this https://github.com/realm/realm-core/pull/5254

**Comment by guramijobava** [comment]
Most of the errors are fixed, but the one is remaining:

```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in RealmCore.o
      ___llvm_profile_runtime_user in Bid.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyone experiencing this error?
